language: r
r: bioc-devel
cache: packages
sudo: required
warnings_are_errors: true
dist: trusty

before_install:
  - mkdir -p ~/.R && echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
  - mkdir -p ~/.R && echo 'options(Ncpus = 2)' > ~/.Rprofile

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev

r_packages:
  - covr
  - pkgdown
  - testthat
  - knitr
  - roxygen2

#r_binary_packages are not part of the cache and will slow down subsequent runs
#r_binary_packages:
#  - devtools
#  - covr
#  - testthat
#  - knitr
#  - roxygen2
#  - git2r
#  - MASS
#  - RSQLite
#  - stringi
#  - xml2
#  - XML
#  - igraph
#  - RCurl
#  - rgl
#  - matrixStats

# before_script:
#   - echo "BiocParallel::register(BiocParallel::SerialParam())" > ~/.Rprofile

# the *.tar.gz is not kept across different jobs, but R CMD build is fast
jobs:
  include:
    - stage: "Build"
      script: R CMD build --no-build-vignettes --no-manual .
      name: "build"
    - stage: "Check"
      script: R CMD build --no-build-vignettes --no-manual . && R CMD check --no-build-vignettes --no-vignettes --no-manual --no-tests MSnbase*tar.gz
      install: skip
      name: "examples"
    - script: R CMD build --no-build-vignettes --no-manual . && R CMD check --no-build-vignettes --no-vignettes --no-manual --no-codoc --no-examples MSnbase*tar.gz
      install: skip
      name: "tests"
    - script: R CMD build . && R CMD check --no-build-vignettes --no-codoc --no-examples --no-tests MSnbase*tar.gz
      install: skip
      name: "vignettes"
    - stage: "codecov"
      script: travis_wait 20 rscript -e 'covr::codecov()'
      install: skip
      name: "codecov"
    - stage: "pkgdown"
      install: skip
      script: travis_wait 20 Rscript -e 'pkgdown::build_site()'
      name: "pkgdown"
      if: branch = master
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_PAT
        keep-history: true
        local-dir: docs
        on:
          branch: master

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

notifications:
  email:
    on_failure: change
    on_success: change
