language: r
r: bioc-devel
cache: packages
sudo: required
warnings_are_errors: true
dist: trusty

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing mzR installation to fail
# see https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189
# workaround stolen from https://github.com/hadley/devtools/blob/1ce84b04568ff7846c3da754f28e7e22a23c8737/.travis.yml#L23-L26
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev

r_binary_packages:
  - devtools
  - covr
  - testthat
  - plyr
  - dplyr
  - pryr
  - gridExtra
  - lattice
  - ggplot2
  - XML
  - scales
  - MASS
  - microbenchmark
  - zoo
  - knitr
  - roxygen2
  - rgl
  - rmarkdown
  - norm
  - shiny
  - git2r
  - bit
  - bit64
  - bitops
  - RSQLite
  - caTools
  - gtools
  - data.table
  - stringi
  - xml2
  - igraph
  - zlibbioc
  - affyio
  - affy
  - preprocessCore
  - MALDIquant
  - ncdf4
  - rhdf5
  - RCurl
  - geometry
  - lubridate
  - FNN
  - e1071
  - mixtools
  - gbm

# before_script:
#   - echo "BiocParallel::register(BiocParallel::SerialParam())" > ~/.Rprofile

jobs:
  include:
    stage: "Build"
      name: "R CMD build"
      script: R CMD build .
    stage: "Check"
      name: "R CMD check examples"
      script: R CMD check --no-build-vignettes --no-vignettes --no-manual --no-tests MSnbase*tar.gz
      name: "R CMD check tests"
      script: R CMD check --no-build-vignettes --no-vignettes --no-manual --no-codoc --no-examples MSnbase*tar.gz

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
  - travis_wait 20 Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change

