language: r
r: bioc-devel
cache:
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
  packages: true
  ccache: true
sudo: required
warnings_are_errors: true
dist: trusty

before_install:
  - mkdir -p ~/.R && echo -e 'MAKEFLAGS = -j2\nCCACHE=ccache\nCC=$(CCACHE) gcc -std=c99 -g -O2 -fPIC\nCXX=$(CCACHE) g++ -std=c++0x -g -O2 -fPIC\nCXX1X=$(CCACHE) g++ -std=c++0x -g -O2 -fPIC\nCXX11=$(CCACHE) g++ -std=c++11 -g -O2 -fPIC\nCXX14=$(CCACHE) g++ -std=c++14 -g -O2 -fPIC\nFC=$(CCACHE) gfortran\nF77=$(CCACHE) gfortran\n' > ~/.R/Makevars
  - mkdir -p ~/.R && echo 'options(Ncpus = 2)' > ~/.Rprofile
  - mkdir -p ~/.ccache && echo -e 'sloppiness = include_file_ctime\nhash_dir = false' > ~/.ccache/ccache.conf

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev

r_binary_packages:
  - devtools
  - covr
  - testthat
  - pkgdown
  - plyr
  - dplyr
  - pryr
  - gridExtra
  - lattice
  - ggplot2
  - XML
  - scales
  - MASS
  - microbenchmark
  - zoo
  - knitr
  - roxygen2
  - rgl
  - rmarkdown
  - norm
  - shiny
  - git2r
  - bit
  - bit64
  - bitops
  - RSQLite
  - caTools
  - gtools
  - data.table
  - stringi
  - xml2
  - igraph
  - MALDIquant
  - ncdf4
  - RCurl
  - geometry
  - lubridate
  - FNN
  - mixtools
  - gbm

# before_script:
#   - echo "BiocParallel::register(BiocParallel::SerialParam())" > ~/.Rprofile

jobs:
  include:
    - stage: "Build"
      name: "R CMD build"
      script: R CMD build --no-build-vignettes --no-manual .
    - stage: "Check"
      script: R CMD check --no-build-vignettes --no-vignettes --no-manual --no-tests MSnbase*tar.gz
      name: "examples"
    - script: R CMD check --no-build-vignettes --no-vignettes --no-manual --no-codoc --no-examples MSnbase*tar.gz
      name: "tests"
    - script: R CMD check --no-codoc --no-examples --no-tests MSnbase*tar.gz
      name: "vignettes"

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
  - travis_wait 20 Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change

